"""user table

Revision ID: 867458234280
Revises: 91a0e54726b9
Create Date: 2024-04-25 21:32:43.555590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867458234280'
down_revision = '91a0e54726b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('ThinkPads',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('ThinkPads',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
