"""users table

Revision ID: aa8d11faa2a8
Revises: 23be62151fb7
Create Date: 2024-04-25 17:20:52.011342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa8d11faa2a8'
down_revision = '23be62151fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ThinkPads', sa.Integer(), nullable=False))
        batch_op.drop_column('thinkpads')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thinkpads', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('ThinkPads')

    # ### end Alembic commands ###
